name: Build and deploy 3

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: linkaaron2
  NODE_VERSION: '18.17.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      # - uses: pnpm/action-setup@v2
      #   name: Install pnpm
      #   with:
      #     version: 8
              
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'pnpm'  

      # - name: Install Dependencies
      #   run: |
      #       pnpm install
      #       pnpm build-link       

      # - name: Zip all files
      #   run: zip next.zip ./apps/web/* ./apps/web/.next -qr

      - name: Zip all files
        #run: zip -r next.zip ../apps/web/* ../apps/web/.next
        working-directory: ./apps/web
        run: zip next.zip ./* ./.next -qr
                   
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./apps/web/next.zip

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app


  # deploy:
  #     runs-on: ubuntu-latest
  #     needs: build
          
  #     steps:

  #       - name: Download artifact from build job
  #         uses: actions/download-artifact@v2
  #         with:
  #           name: node-app

  #       - name: 'Deploy to Azure Web App'
  #         id: deploy-to-webapp
  #         uses: azure/webapps-deploy@v2
  #         with:
  #           app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #           slot-name: 'Production'
  #           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #           package: next.zip