name: Build and deploy 2

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: linkaaron2
  AZURE_WEBAPP_PACKAGE_PATH: './apps/web'
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
              
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: |
          pnpm install -P
          pnpm build-link
        working-directory: ./apps/web          

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./apps/web


  deploy:
      runs-on: ubuntu-latest
      needs: build
          
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: node-app

        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            slot-name: 'Production'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}