name: Build and deploy 2

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: linkaaron2
  AZURE_WEBAPP_PACKAGE_PATH: 'apps/web'
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: pnpm install, build
        run: |
          pnpm install
          pnpm run build
        # working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}