name: Build and Deploy to Azure Web App

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: linkaaron2
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
              
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'  

      - name: Install & Build
        run: |
            pnpm install
            pnpm build-link       

      - name: Zip all files
        working-directory: ./apps/web
        run: zip next.zip ./* .next .env -qr
      
      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     path: ./apps/web

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./apps/web/next.zip

      - name: Delete zip file
        run: rm ./apps/web/next.zip