name: Build and Deploy to Azure Web App

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: linkaaron2
  NODE_VERSION: '18.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: |
            - recursive: true
              
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'  

      - name: Build
        run:  | 
              pnpm add @swc/helpers
              pnpm build-link
        working-directory: ./apps/web                       

      - name: Zip files        
        run: zip -qr next.zip ./apps/web* .apps/.next ./ecosystem.config.js ./package.json -x ./apps/docs*

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: next.zip     

      - name: Delete zip file
        run: rm next.zip